const mangayomiSources=[{name:"JKAnime Comunidad",lang:"es",baseUrl:"https://jkanime.net",apiUrl:"",iconUrl:"https://cdn.jkanime.net/logo_jk.png",typeSource:"single",itemType:1,id:9000000102,version:"0.5.0",dateFormat:"",dateFormatLocale:"",pkgPath:"anime/src/es/jkanime.js"}];

class DefaultExtension extends MProvider{
 constructor(){super();this.client=new Client();}
 clean(s){return(s||"").replace(/\s+/g," ").trim();}
 abs(u){if(!u)return"";if(/^https?:\/\//i.test(u))return u;if(u.startsWith("//"))return"https:"+u;if(u.startsWith("/"))return this.source.baseUrl+u;return this.source.baseUrl+"/"+u;}
 async getDoc(url,ref){const r=await this.client.get(url,{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36","Referer":ref||this.source.baseUrl+"/"});return new Document(r.body);}
 card(e){const a=e.selectFirst("a[href]");if(!a)return null;const h=a.attr("href")||"";const link=this.abs(h);if(!/^https?:\/\/jkanime\.net\/[^/?#]+\/?$/i.test(link))return null;const name=this.clean(a.attr("title")||a.text);if(!name)return null;const img=e.selectFirst("img");return{name,imageUrl:img?(img.attr("data-src")||img.attr("data-lazy-src")||img.attr("src")||""):"",link};}
 async htmlList(url){const d=await this.getDoc(url),out=[],seen={};const selectors=["div.portada-box","div#conb","article",".item"];for(const sel of selectors)for(const e of d.select(sel)){const x=this.card(e);if(x&&!seen[x.link]){seen[x.link]=1;out.push(x);}}if(!out.length){for(const a of d.select("h5 a[href],h4 a[href],h3 a[href]")){const h=a.attr("href")||"",link=this.abs(h);if(!/^https?:\/\/jkanime\.net\/[^/?#]+\/?$/i.test(link))continue;const name=this.clean(a.attr("title")||a.text);if(name&&!seen[link]){seen[link]=1;let p=a.parent();const im=p?p.selectFirst("img"):null;out.push({name,imageUrl:im?(im.attr("data-src")||im.attr("src")||""):"",link});}}}return{list:out,hasNextPage:out.length>0};}
 async getPopular(page){return await this.htmlList(page&&page>1?`${this.source.baseUrl}/top/${page}/`:this.source.baseUrl+"/top/");}
 async getLatestUpdates(page){return await this.htmlList(page&&page>1?`${this.source.baseUrl}/directorio/${page}/`:this.source.baseUrl+"/directorio/");}
 async search(query,page){const q=this.clean(query).replace(/\s+/g,"_");const url=`${this.source.baseUrl}/buscar/${encodeURIComponent(q)}/`;return await this.htmlList(url);}
 async getDetail(url){const d=await this.getDoc(url),nameEl=d.selectFirst("h1")||d.selectFirst("h2"),syn=d.selectFirst(".sinopsis-box p")||d.selectFirst("p.sinopsis")||d.selectFirst("#ainfo p");const detail={name:this.clean(nameEl?nameEl.text:""),link:url,imageUrl:"",description:this.clean(syn?syn.text:""),author:"",artist:"",genre:[],status:5,episodes:[]};const cover=d.selectFirst("img");if(cover)detail.imageUrl=cover.attr("data-src")||cover.attr("data-lazy-src")||cover.attr("src")||"";d.select("a[href*='/genero/']").forEach(a=>{const g=this.clean(a.text);if(g&&!detail.genre.includes(g))detail.genre.push(g);});const seen={};d.select("a[href]").forEach(a=>{const h=a.attr("href")||"",m=h.match(/\/([^/?#]+)\/(\d+)\/?$/);if(!m)return;const n=Number(m[2]);if(n>0&&n<10000&&!seen[n]){seen[n]=1;detail.episodes.push({name:`Episodio ${n}`,url:this.abs(h),scanlator:"JKAnime"});}});detail.episodes.sort((a,b)=>Number(a.name.match(/\d+/)[0])-Number(b.name.match(/\d+/)[0]));return detail;}
 media(html,base){const out=[],add=u=>{if(!u)return;u=u.replace(/&amp;/g,"&").replace(/\\\//g,"/");if(!/^https?:/i.test(u))return;if(/\.(?:m3u8|mp4)(?:[?#]|$)/i.test(u)&&!out.some(x=>x.url===u))out.push({url:u,originalUrl:u,quality:"JKAnime"});};let m;for(const r of [/<source[^>]+src=["']([^"']+)["']/gi,/(?:file|src|source)\s*[:=]\s*["']([^"']+)["']/gi,/(["'])(https?:\/\/[^"' ]+\.(?:m3u8|mp4)(?:\?[^"' ]*)?)\1/gi])while((m=r.exec(html)))add(m[2]||m[1]);return out;}
 async getVideoList(url){const r=await this.client.get(url,{"User-Agent":"Mozilla/5.0","Referer":this.source.baseUrl+"/"});let out=this.media(r.body,url);const d=new Document(r.body);const refs=[];d.select("iframe,embed,video,source,[data-src],[data-url],[data-player]").forEach(e=>{const u=e.attr("src")||e.attr("data-src")||e.attr("data-url")||e.attr("data-player");if(u&&!refs.includes(u))refs.push(u);});for(const u of refs){try{const rr=await this.client.get(this.abs(u),{"User-Agent":"Mozilla/5.0","Referer":url});for(const v of this.media(rr.body,this.abs(u)))if(!out.some(x=>x.url===v.url))out.push(v);}catch(_){}}return out;}
 getFilterList(){return[];}
}
