const client = new Client();
const BASE_URL = "https://jkanime.net";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36";
function headers(referer){return {"User-Agent":UA,"Referer":referer||BASE_URL+"/","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"};}
function abs(u,b){if(!u)return "";if(/^https?:\/\//i.test(u))return u;if(u.startsWith("//"))return "https:"+u;if(u.startsWith("/"))return BASE_URL+u;return (b||BASE_URL+"/").replace(/\/[^/]*$/,"/")+u;}
function clean(s){return(s||"").replace(/\s+/g," ").trim();}
function dec(s){return(s||"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x27;/gi,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
async function doc(u,r){const x=await client.get(u,headers(r));return new Document(x.body);}
function img(el){const i=el&&el.selectFirst("img");return i?abs(i.attr("data-src")||i.attr("data-lazy-src")||i.attr("src")):"";}
function item(el){const a=el.selectFirst("h2.portada-title a")||el.selectFirst("a.let-link")||el.selectFirst("a");if(!a||!a.attr("href"))return null;return{name:clean(a.attr("title")||a.text),url:abs(a.attr("href")),link:abs(a.attr("href")),imageUrl:img(el)};}
async function listing(u){const d=await doc(u),o=[];d.select("div.portada-box").forEach(e=>{const x=item(e);if(x&&x.name)o.push(x);});return o;}
async function getPopular(page){page=Number(page||1);const l=await listing(page===1?BASE_URL+"/":BASE_URL+"/pagina/"+page+"/");return{list:l,hasNextPage:l.length>0};}
async function getLatest(page){return getPopular(page);}
async function search(q,page){const s=encodeURIComponent(clean(q));let l=[];for(const u of [BASE_URL+"/buscar/"+s+"/",BASE_URL+"/buscar/"+s+"/"+Number(page||1)+"/"]){try{l=await listing(u);if(l.length)break;}catch(_){}}return{list:l,hasNextPage:l.length>0};}
function epHref(h){const m=(h||"").match(/\/([^/?#]+)\/(\d+)\/?$/);return m?{slug:m[1],number:Number(m[2])}:null;}
function stat(s){s=clean(s).toLowerCase();if(s.includes("final")||s.includes("complet"))return 1;if(s.includes("cancel"))return 3;if(s.includes("paus"))return 2;if(s.includes("emision")||s.includes("emisión")||s.includes("ongoing"))return 0;return 5;}
async function getDetail(u){const d=await doc(u),t=d.selectFirst("h1")||d.selectFirst(".serie-title"),sy=d.selectFirst(".sinopsis-box p.pc")||d.selectFirst(".sinopsis-box p")||d.selectFirst("#ainfo p"),g=[],e=[],seen={};d.select("a").forEach(a=>{const h=a.attr("href")||"",p=epHref(h),tx=clean(a.text);if(p&&p.number>0&&!seen[p.number]){seen[p.number]=1;e.push({name:"Episodio "+p.number,url:abs(h),scanlator:"JKAnime",dateUpload:null});}if(tx&&h.includes("/genero/")&&!g.includes(tx))g.push(tx);});e.sort((a,b)=>Number(a.name.match(/\d+/)[0])-Number(b.name.match(/\d+/)[0]));let st="";d.select(".info-field").forEach(x=>{if(/estado/i.test(clean(x.text)))st=x.text;});return{title:clean(t?t.text:""),description:clean(sy?sy.text:""),author:"",genre:g,status:stat(st),episodes:e};}
function players(html,base){const r=[],add=(u,l)=>{u=abs(dec(u).replace(/\\u002F/g,"/").replace(/\\\//g,"/"),base);if(/^https?:\/\//i.test(u)&&!r.some(x=>x.url===u))r.push({url:u,label:l||"JKAnime"});};const d=new Document(html);d.select("iframe,embed,video,source").forEach(x=>add(x.attr("src")||x.attr("data-src")||x.attr("data-url")||x.attr("data-video")||x.attr("file"),"Player"));d.select("[data-url],[data-src],[data-video],[data-iframe],[data-player]").forEach(x=>["data-url","data-src","data-video","data-iframe","data-player"].forEach(a=>add(x.attr(a),"Player")));const re=/(?:https?:)?\/\/[^"'\\\s<>]+/gi;let m;while((m=re.exec(html))!==null)if(/iframe|embed|player|video|stream|m3u8|mp4|desu|magi/i.test(m[0]))add(m[0],"Player");return r;}
function media(html,base){const o=[],add=(u,q)=>{u=abs(dec(u).replace(/\\u002F/g,"/").replace(/\\\//g,"/"),base);if(u&&!o.some(x=>x.url===u))o.push({url:u,originalUrl:u,quality:q||"JKAnime"});};for(const re of [/<source[^>]+src=["']([^"']+)["']/gi,/(?:file|src|source)\s*[:=]\s*["']([^"']+)["']/gi,/["'](https?:\/\/[^"' ]+\.(?:m3u8|mp4)(?:\?[^"' ]*)?)["']/gi]){let m;while((m=re.exec(html))!==null)if(/\.(m3u8|mp4)(?:[?#]|$)/i.test(m[1]))add(m[1],"JKAnime");}return o;}
async function resolve(u,ep,label){try{const r=await client.get(u,headers(ep)),m=media(r.body,u);if(m.length){m.forEach(x=>x.quality=label+" · "+x.quality);return m;}for(const p of players(r.body,u)){try{const rr=await client.get(p.url,headers(u)),n=media(rr.body,p.url);if(n.length){n.forEach(x=>x.quality=label+" · "+x.quality);return n;}}catch(_){}}}catch(_){ }return[];}
async function getVideoList(u){const r=await client.get(u,headers(BASE_URL+"/")),ps=players(r.body,u),out=[];ps.sort((a,b)=>(/desu|magi/i.test(a.url)?0:1)-(/desu|magi/i.test(b.url)?0:1));for(const p of ps){const label=/desu/i.test(p.url)?"Desu":/magi/i.test(p.url)?"Magi":"JKAnime",m=await resolve(p.url,u,label);m.forEach(x=>{if(!out.some(y=>y.url===x.url))out.push(x);});}if(!out.length)media(r.body,u).forEach(x=>out.push(x));return out;}
async function getFilterList(){return[];}
